/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        branco: "var(--branco)",
        cinza: "var(--cinza)",
        "cinza-secondrio": "var(--cinza-secondrio)",
        // "cores-container-fundo": "var(--cores-container-fundo)",
        "cores-dourado": "var(--cores-dourado)",
        "cores-fonte": "var(--cores-fonte)",
        "cores-fonte-p-gina": "var(--cores-fonte-p-gina)",
        "cores-fundo": "var(--cores-fundo)",
        "cores-laranja": "var(--cores-laranja)",
        "cards-container-fundo": "var(--cards-conteiner-fundo)",
        dourado: "var(--dourado)",
        laranja: "var(--laranja)",
        primaria: "var(--primaria)",
      },
      fontFamily: {
        "fontes-fonte-grande-bold": "var(--fontes-fonte-grande-bold-font-family)",
        "fontes-fonte-grande-bold-uppercase": "var(--fontes-fonte-grande-bold-uppercase-font-family)",
        "fontes-fonte-grande-light": "var(--fontes-fonte-grande-light-font-family)",
        "fontes-fonte-grande-light-uppercase": "var(--fontes-fonte-grande-light-uppercase-font-family)",
        "fontes-fonte-grande-regular": "var(--fontes-fonte-grande-regular-font-family)",
        "fontes-fonte-grande-regular-upeercase": "var(--fontes-fonte-grande-regular-upeercase-font-family)",
        "fontes-fonte-m-dia-bold": "var(--fontes-fonte-m-dia-bold-font-family)",
        "fontes-fonte-m-dia-bold-uppercase": "var(--fontes-fonte-m-dia-bold-uppercase-font-family)",
        "fontes-fonte-m-dia-light": "var(--fontes-fonte-m-dia-light-font-family)",
        "fontes-fonte-m-dia-light-uppercase": "var(--fontes-fonte-m-dia-light-uppercase-font-family)",
        "fontes-fonte-m-dia-regular": "var(--fontes-fonte-m-dia-regular-font-family)",
        "fontes-fonte-m-dia-regular-uppercase": "var(--fontes-fonte-m-dia-regular-uppercase-font-family)",
        "fontes-fonte-normal-bold": "var(--fontes-fonte-normal-bold-font-family)",
        "fontes-fonte-normal-light": "var(--fontes-fonte-normal-light-font-family)",
        "fontes-fonte-normal-regular": "var(--fontes-fonte-normal-regular-font-family)",
        "fontes-fonte-normal-regular-underline": "var(--fontes-fonte-normal-regular-underline-font-family)",
        "fontes-fonte-normal-uppercase": "var(--fontes-fonte-normal-uppercase-font-family)",
        "fontes-fonte-normal-uppercase-bold": "var(--fontes-fonte-normal-uppercase-bold-font-family)",
        "fontes-fonte-normal-uppercase-regular": "var(--fontes-fonte-normal-uppercase-regular-font-family)",
        "fontes-fonte-normal-uppercase-underline": "var(--fontes-fonte-normal-uppercase-underline-font-family)",
        "h1-bold": "var(--h1-bold-font-family)",
        "h1-semi-bold": "var(--h1-semi-bold-font-family)",
        "h2-bold": "var(--h2-bold-font-family)",
        "h2-semi-bold": "var(--h2-semi-bold-font-family)",
        "h3-bold": "var(--h3-bold-font-family)",
        "h3-semi-bold": "var(--h3-semi-bold-font-family)",
        "h4-bold": "var(--h4-bold-font-family)",
        "h4-semi-bold": "var(--h4-semi-bold-font-family)",
        "h5-bold": "var(--h5-bold-font-family)",
        "h5-semi-bold": "var(--h5-semi-bold-font-family)",
      },
    },
  },
  plugins: [],
};
